baseURL            = "http://localhost:1313"
languageCode       = "en"
title              = "Verdana's Notebook"
theme              = "hugo-verdana"
enableRobotsTXT    = true
canonifyURLs       = true
hasCJKLanguage     = true
publishDir         = "public"


# Code syntax highlight
pygmentsCodefences = true
pygmentsStyle      = "tango"

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics   = "UA-1900757-1"

# Copyright of your post
copyright = "本作品采用<a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">知识共享署名 4.0 国际许可协议</a>进行许可。"

# Initial site menu, you can extend menu with content.
[[menu.main]]
    name       = "首页"
    weight     = 10
    identifier = "home"
    url        = "/"

[[menu.main]]
    name       = "工作"
    weight     = 20
    identifier = "works"
    url        = "https://github.com/verdana"

[[menu.main]]
    name       = "标签"
    weight     = 30
    identifier = "tags"
    url        = "/tags/"

[params]
    author      = "verdana"
    avatar      = "/img/avatar.jpg"
    seotitle    = "Verdana's Notebook"
    subtitle    = "~ To be better every single day ~"
    description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
    paginate    = 10

    # Choose your social networks
    email    = "verdana.cn@gmail.com"
    github   = "verdana"
    twitter  = "verdana"
    linkedin = "verdana"
    weibo    = "verdano"
    wechat   = "/img/qrcode.jpg"        # Replace with your wechat qrcode image

    # facebook  = "facebook_username"
    # google    = "googlplus_id_number"
    # instagram = "instagram_username"
    # youtube   = "youtube_username"
    # vimeo     = "vimeo_username"
    # medium    = "medium_username"
    # quora     = "quora_username"
    # pinterest = "pinterest_username"
    # dribbble  = "dribbble_username"
    # behance   = "behance_username"
    # jsfiddle  = "jsfiddle_username"
    # codepen   = "codepen_username"
    # zhihu     = "zhihu_username"
    # douban    = "douban_username"
    # bilibili  = "bilibili_id_number"

    # Changyan Comments (China Only)
    changyan     = false
    changyanId   = ""
    changyanConf = ""

    # Google Webmaster
    # https://www.google.com/webmasters/
    googleSiteVerification = ""

    # Bing Webmaster
    # https://www.bing.com/toolbox/webmaster/
    msValidate = ""

    # Sogou Webmaster (China Only)
    # http://zhanzhang.sogou.com/
    # sogouSiteVerification = "m2jktMQTZm"

    # ICP Number (China Only)
    # ICP = "苏ICP备16005986号-2"
